apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 505237732499.dkr.ecr.ap-northeast-2.amazonaws.com/member-service
  newName: 505237732499.dkr.ecr.ap-northeast-2.amazonaws.com/member-service
  newTag: aabbcd02
resources:
- ../../base
patchesStrategicMerge:
- member-deployment-patch.yaml
- member-service-patch.yaml
