---
apiVersion: v1
kind: Service
metadata:
  name: sgi-edu-member-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
  labels:
    env: prod
spec:
  selector:
    app: sgi-edu-member-service-deployment